spring.application.name=backend

spring.datasource.url=jdbc:h2:mem:mydb3
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


#to see all the queries being run in console we do
spring.jpa.show-sql=true


#we need jpa to create table and we have 2 options
#1 to create table everytimg we run
#2.create table if not present and then update rest of the time, h2 me set karne ka no need but ill do it anyways
spring.jpa.hibernate.ddl-auto=update

#to delay the process of initializing of sql queries (file data.sql wali) we do
spring.jpa.defer-datasource-initialization=true;
#by this pehle table banega fir initialize hoga