spring.application.name=springsec01

spring.security.user.name=harsh
spring.security.user.password=harsh123


#DBMS configure karlo
spring.datasource.url=jdbc:postgresql://localhost:5433/mydb2
spring.datasource.username=postgres
spring.datasource.password=Har@123

spring.jpa.hibernate.ddl-auto=update