spring.application.name=spring07

spring.datasource.url=jdbc:h2:mem:mydb2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#to see all the queries being run in console we do
spring.jpa.show-sql=true