package com.example.backend.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Generated;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;

//NOTE-> saare names frontend ke hisab se bana na yaar banckodi hoti nai toh
//give names according to addProduct.jsx
//const [product, setProduct] = useState({
//    name: "",
//            brand: "",
//            description: "",
//            price: "",
//            category: "",
//            stockQuantity: "",
//            releaseDate: "",
//            productAvailable: false,
//});
//iske similar hi dena


//iss class ka table banana hai na, toh uske liye isko entity banana padega
@Entity
//constructor getter setter bakchodi khud se banane ke liye ye needed
@Data
//bharne ke liye all args consturctor needed
@AllArgsConstructor
// hibernate ko object banane ke liye ye lagega
@NoArgsConstructor
public class product {
//    primary key ke upar id banana need
    @Id
//    bhai we need id to be autogenerated nai toh chud jaenge khud dete dete, for that
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    private String name;
    private String description;
    private String brand;
//    since price can be really big amt
    private BigDecimal price;
    private String category;

//    date bhi apne hisab se chahiye using jackson library\
//    basically ki string me store karo and pattern bata diye apan
    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern = "yyyy-MM-dd")
    private Date releaseDate;
    private boolean productAvailable;
    private int stockQuantity;


//    image ke liye we need 3 things, name, type and data/bits
    private String imageName;
    private String imageType;
//    image data to be store in large Object, uske liye @Lob
    @Lob
    private byte[] imageData;

}
