spring.application.name=spring01

#url daal do
spring.datasource.url=jdbc:mysql://localhost:3306/mydb1
#username daal do
spring.datasource.username=root
#passwd daal do
spring.datasource.password=Har@123

#driver ka name daalna padega, no need to biheart all this, popup aayega
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver